### ISSUE TITLE
linuxbrew planemo 4.0 installation failure

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/planemo#77]
Is it just me? Did the good folks at linuxbrew just 'fix' something? 

Planemo 0.4 seems to be trying to install itself to /home/rlazarus/.linuxbrew/Cellar/planemo/0.4.0 - the Cellar layer is new since 0.3?

This is after updating linuxbrew - possibly a bad idea right now
doing `brew install planemo`on ubuntu 14.04 using linuxbrew:

```
rlazarus@rlazarus-UX31A:~$ brew install planemo
==> Installing planemo from galaxyproject/homebrew-tap
==> Installing planemo dependency: libyaml
==> Downloading http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz
Already downloaded: /home/rlazarus/.cache/Homebrew/libyaml-0.1.6.tar.gz
==> Downloading https://bitbucket.org/xi/libyaml/commits/2b9156756423e967cfd09a61d125d883fca6f4f2/raw/
Already downloaded: /home/rlazarus/.cache/Homebrew/libyaml--patch-174dbe1f5161853cdb1c6ba94df6a826cf25870c
==> Patching
patching file src/scanner.c
==> ./configure --prefix=/home/rlazarus/.linuxbrew/Cellar/libyaml/0.1.6_1
==> make install
/home/rlazarus/.linuxbrew/Cellar/libyaml/0.1.6_1: 7 files, 344K, built in 10 seconds
==> Installing planemo
==> Downloading https://github.com/galaxyproject/planemo/archive/0.4.0.tar.gz
Already downloaded: /home/rlazarus/.cache/Homebrew/planemo-0.4.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.tar.gz
Already downloaded: /home/rlazarus/.cache/Homebrew/planemo--pyyaml-3.10.tar.gz
Warning: Language::Python.setup_install is deprecated.
If you are a formula author, please use
  system "python", *Language::Python.setup_install_args(prefix)
instead.
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: -c --help [cmd1 cmd2 ...]
   or: -c --help-commands
   or: -c cmd --help

error: option --single-version-externally-managed not recognized
```

followed by more of the same and finally
```
error: option --single-version-externally-managed not recognized
Warning: tried to install empty array to /home/rlazarus/.linuxbrew/Cellar/planemo/0.4.0/bin
/home/rlazarus/.linuxbrew/Cellar/planemo/0.4.0: 4 files, 56K, built in 15 seconds
```

**Comment by jmchilton** [comment]
Okay - thanks for the report. It should be fixed after another `brew update`  - sorry about that.

**Comment by fubar2** [comment]
Nothing reported with brew doctor but I'm still seeing the unknown option error --single-version-externally-managed:

```
rlazarus@rlazarus-UX31A:~$ brew uninstall planemo
Uninstalling /home/rlazarus/.linuxbrew/Cellar/planemo/0.4.0...
rlazarus@rlazarus-UX31A:~$ brew install planemo
==> Installing planemo from galaxyproject/homebrew-tap
==> Downloading https://github.com/galaxyproject/planemo/archive/0.4.0.tar.gz
Already downloaded: /home/rlazarus/.cache/Homebrew/planemo-0.4.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.tar.gz
Already downloaded: /home/rlazarus/.cache/Homebrew/planemo--pyyaml-3.10.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/home/rlazarus/.linuxbrew/Cellar/planemo/0.4.0/libexec/vendor --si
   or: -c --help [cmd1 cmd2 ...]
   or: -c --help-commands
   or: -c cmd --help

error: option --single-version-externally-managed not recognized

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/galaxyproject/homebrew-tap/issues

rlazarus@rlazarus-UX31A:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /home/rlazarus/.linuxbrew/opt/pkg-config

```

**Comment by saketkc** [comment]
Shot in the dark: Can you updated your `pip` to latest stable?

**Comment by jmchilton** [comment]
Another shot in the dark - can you try - `brew install ansible`. That is the recipe pattern I am following so if there is some incompatibility between `pip` and `brew` that would detect it - but if the recipe installs then it is likely I am doing something bad in recipe.

**Comment by fubar2** [comment]
Looks like @saketkc got it right - see http://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind

After much pfaffing about with apt and uninstalling pip and friends from my messy old ubuntu 14.04 laptop, the solution appears to have been to revert to using the old easy_install python script to install pip :

```
sudo easy_install pip
```

For future reference: Looks like the 14.04 ubuntu pip package is out of date. That got rid of the problem with the --single-version-externally-managed parameter not being recognised.

brew install ansible
and
brew install planemo worked fine

Thanks everyone - at least we now know what to do if anyone reports that parameter being invalid.
